# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: {{ include "nemotron3.fullname" . }}
  labels:
    {{- include "nemotron3.labels" . | nindent 4 }}
spec:
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  authSecret: {{ .Values.global.authSecretName | quote }}
  labels:
    {{- include "nemotron3.selectorLabels" . | nindent 4 }}
  {{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/path: "/v1/metrics"
  {{- end }}
  env:
    - name: NIM_PASSTHROUGH_ARGS
      valueFrom:
        configMapKeyRef:
          name: {{ include "nemotron3.fullname" . }}-nim-env
          key: NIM_PASSTHROUGH_ARGS
          optional: true
  {{- if .Values.metrics.enabled }}
  metrics:
    enabled: true
  {{- end }}
  expose:
    service:
      port: {{ .Values.service.port }}
      type: {{ .Values.service.type }}
  image:
    pullPolicy: {{ .Values.image.pullPolicy }}
    pullSecrets:
      - {{ .Values.global.pullSecretName | quote }}
    repository: {{ .Values.image.repository }}
    tag: {{ .Values.image.tag | quote }}
  replicas: {{ .Values.replicas }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  storage:
    nimCache:
      name: {{ include "nemotron3.fullname" . }}
